spring:
  profiles:
    default: dev

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.port:6379}

  elasticsearch:
    connection-timeout: 3s
    uris: ${elasticsearch.host:localhost}

  config:
    import: optional:file:.env[.properties]

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_BUCKET}
