spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/gsg}
    username: ${db.username:root}
    password: ${db.password:root}

  jpa:
    hibernate:
      ddl-auto: update
