spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/gsg}
    username: ${db.username:root}
    password: ${db.password:root}

  jpa:
    hibernate:
      ddl-auto: update
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:secretkey}
      embedding:
        options:
          model: text-embedding-3-small



