spring:
  profiles:
    default: dev

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.port:6379}

  elasticsearch:
    connection-timeout: 3s
    uris: ${elasticsearch.host:localhost}